// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHIo8B5X2VpTVBKLrnIea8x__tsCdkOJU',
    appId: '1:484292207161:web:5ebbdc3f101b4795b3a3e8',
    messagingSenderId: '484292207161',
    projectId: 'smart-sabaq',
    authDomain: 'smart-sabaq.firebaseapp.com',
    storageBucket: 'smart-sabaq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2lw4k9ofoJi9RFL1PZk0_9YJARy0C-wo',
    appId: '1:484292207161:android:65335331acc69d91b3a3e8',
    messagingSenderId: '484292207161',
    projectId: 'smart-sabaq',
    storageBucket: 'smart-sabaq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcVdh1TzFQH70x8rGEwVzAQT9suFnrbs',
    appId: '1:484292207161:ios:7c6f1e693c051831b3a3e8',
    messagingSenderId: '484292207161',
    projectId: 'smart-sabaq',
    storageBucket: 'smart-sabaq.firebasestorage.app',
    iosBundleId: 'kz.sovetzhanov.smartSabaq',
  );
}
